# Generated by Django 5.1.6 on 2025-02-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="No description available"),
        ),
    ]
